### ISSUE TITLE
Great project. I use it daily.

### ISSUE THREAD

**Issue by nathanaelbonfim** [ShaanCoding/Pomodoro-Timer#2]
I was searching for an alternative that did not use Electron and found this. Thanks, man! It is really helpful. 

By the way, inspired by your project I'm building my own Pomodoro app using C and raylib for studying purposes.

Ps.: I don't know if issues are meant to be used this way. If not, you close/remove it.

Regards,
Nathanael

**Comment by ShaanCoding** [comment]
Hey nathanael, thanks for writing this, I really appreciate it!

Always glad to see that someones using one of my open-source projects, which always makes writing them worth it. Awesome to hear that you're working on your own Pomodoro app, I remember that this app was definitely one of the projects that really inspired me to get into development, I hope you enjoy your project the same as it was to me.

Feel free to ask me anything if you've got any questions, I'm more than happy to help with anything if I can.

Regards,
Shaan
